### ISSUE TITLE
Replace images in website homepage with the following

### ISSUE THREAD

**Issue by upulw2020** [OpenArchive/web-next#4]
**Replace the current images in the homepage with the following**
![main4](https://github.com/user-attachments/assets/469c84cb-ab9c-4364-a18a-877f6365eaee)
![main3](https://github.com/user-attachments/assets/c3b71f9a-22a5-4baa-a9dc-9d6f68d4dca2)
![main2](https://github.com/user-attachments/assets/9ab20e3f-0f44-4046-a1d0-8b9bbdd4ad92)
![main1](https://github.com/user-attachments/assets/f0137571-863d-4601-be3e-3a3f89933366)

**Order for images**
![Home](https://github.com/user-attachments/assets/55dd7515-6d2f-4f24-b2ef-29e6b39515de)

**Comment by rapuckett** [comment]
Resolved in [567b54b](https://github.com/OpenArchive/web-next/commit/567b54bee5024e1e97fa68f5aa8f1cfd4a7877a3)
